101=SELECT ORGID,ORGTYPEID,NAME,DESCRIPTION,ADDRESSID,PARENTORGID,CREATED,UPDATED FROM ORGANIZATION WHERE ORGID =? AND STATE=0
102=INSERT INTO ORGANIZATION(ORGTYPEID,NAME,DESCRIPTION,ADDRESSID,PARENTORGID,CREATED,UPDATED,STATE) VALUES (?,?,?,?,?,NOW(),NOW(),0) ON DUPLICATE KEY UPDATE ORGTYPEID=?,NAME=?, DESCRIPTION=?,ADDRESSID=?,PARENTORGID=?,UPDATED=NOW(),STATE=0
104=UPDATE ORGANIZATION SET STATE=1 WHERE ORGID=? AND STATE=0
105=SELECT ORGID  FROM ORGANIZATION WHERE NAME=?
106=SELECT ORGID,ORGTYPEID,NAME,DESCRIPTION,ADDRESSID,PARENTORGID,CREATED,UPDATED FROM ORGANIZATION WHERE ORGID = (SELECT PARENTORGID FROM ORGANIZATION WHERE ORGID=? AND STATE=0) AND STATE=0
107=SELECT ORGID,ORGTYPEID,NAME,DESCRIPTION,ADDRESSID,PARENTORGID,CREATED,UPDATED FROM ORGANIZATION WHERE PARENTORGID = ? AND STATE=0
108=SELECT ORGID FROM ORGANIZATION WHERE ORGID =? AND STATE=0


109=SELECT * FROM (SELECT O.ORGID AS ID,O.NAME,P.ORGID AS PARENTID,P.NAME AS PARENTNAME,O.ORGTYPEID FROM ORGANIZATION O LEFT OUTER JOIN ORGANIZATION P ON O.PARENTORGID = P.ORGID AND O.STATE =0 AND P.STATE=0) X LIMIT ?, ?
110=SELECT * FROM (SELECT O.ORGID AS ID,O.NAME,P.ORGID AS PARENTID,P.NAME AS PARENTNAME,O.ORGTYPEID FROM ORGANIZATION O LEFT OUTER JOIN ORGANIZATION P ON O.PARENTORGID = P.ORGID AND O.STATE =0 AND P.STATE=0 WHERE O.ORGTYPEID=?) X LIMIT ?, ?
112=SELECT * FROM (SELECT O.ORGID AS ID,O.NAME,P.ORGID AS PARENTID,P.NAME AS PARENTNAME,O.ORGTYPEID FROM ORGANIZATION O LEFT OUTER JOIN ORGANIZATION P ON O.PARENTORGID = P.ORGID AND O.STATE =0 AND P.STATE=0 WHERE O.ORGTYPEID=?  O.NAME LIKE ?) X LIMIT ?, ?
111=SELECT * FROM (SELECT O.ORGID AS ID,O.NAME,P.ORGID AS PARENTID,P.NAME AS PARENTNAME,O.ORGTYPEID FROM ORGANIZATION O LEFT OUTER JOIN ORGANIZATION P ON O.PARENTORGID = P.ORGID AND O.STATE =0 AND P.STATE=0 WHERE O.NAME LIKE ?) X LIMIT ?, ?

