DROP TABLE IF EXISTS WYTAL_EXCEPTION;
DROP TABLE IF EXISTS MEDICAL_RECORD_NOTES;
DROP TABLE IF EXISTS MEDICAL_RECORD_NUMBER;
DROP TABLE IF EXISTS MEDICAL_RECORD_RECIPIENT;
DROP TABLE IF EXISTS MEDICAL_RECORD_HISTORY;

DROP TABLE IF EXISTS MEDICAL_RECORD;
DROP TABLE IF EXISTS AUTHENTICATION;
DROP TABLE IF EXISTS AUDIT_LOG;
DROP TABLE IF EXISTS USER_PERSON_ASSOCIATION;
DROP TABLE IF EXISTS USER_ROLE;
DROP TABLE IF EXISTS USER;



DROP TABLE IF EXISTS EMR_MEDICAREID;



DROP TABLE IF EXISTS PERSONNEL_ORGANIZATION_ACCESS;
DROP TABLE IF EXISTS PERSONNEL_ORGANIZATION;


DROP TABLE IF EXISTS PERSONNEL_PROVIDER_IDENTIFIER;
DROP TABLE IF EXISTS PERSONNEL;
DROP TABLE IF EXISTS PERSON_CONTACT;
DROP TABLE IF EXISTS PERSON_ADDRESS;
DROP TABLE IF EXISTS PERSON_RELATIONSHIP;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS ORGANIZATION_CONTACT;

DROP TABLE IF EXISTS ORGANIZATION;
DROP TABLE IF EXISTS ORGANIZATION_TYPE;


DROP TABLE IF EXISTS ROLE_ACCESS;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS REPORT_TYPE; 
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS CONTACT_TYPE;
DROP TABLE IF EXISTS ADDRESS_TYPE;

DROP TABLE IF EXISTS RELATION_TYPE;

DROP TABLE IF EXISTS PROVIDER_IDENTIFIER_TYPE;
DROP TABLE IF EXISTS MEDICAL_REPORT_STATE;
