INSERT INTO RELATION_TYPE( NAME, DESCRIPTION,CREATED,UPDATED) VALUES ('Father','Father', NOW(),NOW());
INSERT INTO RELATION_TYPE( NAME, DESCRIPTION,CREATED,UPDATED) VALUES ('Mother','Mother', NOW(),NOW());
INSERT INTO RELATION_TYPE( NAME, DESCRIPTION,CREATED,UPDATED) VALUES ('Son','Son', NOW(),NOW());
INSERT INTO RELATION_TYPE( NAME, DESCRIPTION,CREATED,UPDATED) VALUES ('Daughter','Daughter', NOW(),NOW());





INSERT INTO ROLE (NAME, DESCRIPTION) VALUES('ADMIN','SUPERVISOR');
INSERT INTO ROLE (NAME, DESCRIPTION) VALUES('DOCTOR','DOCTOR');
INSERT INTO ROLE (NAME, DESCRIPTION) VALUES('NURSE PRACTITIONER','Nurse practitioner');
INSERT INTO ROLE (NAME, DESCRIPTION) VALUES('RADIOLOGIST','Radiologist');
INSERT INTO ROLE (NAME, DESCRIPTION) VALUES('PATIENT ','Patient');




INSERT INTO ROLE_ACCESS (ROLEID, API) SELECT  ROLEID,'createAccount' FROM ROLE WHERE NAME='ADMIN';
INSERT INTO ROLE_ACCESS (ROLEID, API) SELECT  ROLEID,'listAllReports' FROM ROLE WHERE NAME='ADMIN';
INSERT INTO ROLE_ACCESS (ROLEID, API) SELECT  ROLEID, 'updateMedicalReport' FROM ROLE WHERE NAME='ADMIN';
INSERT INTO ROLE_ACCESS (ROLEID, API) SELECT  ROLEID, 'listAllReportsByPersonnel' FROM ROLE WHERE NAME='ADMIN';
INSERT INTO ROLE_ACCESS (ROLEID, API) SELECT  ROLEID,'listAllReportsByPersonnel' FROM ROLE WHERE NAME='DOCTOR';
INSERT INTO ROLE_ACCESS (ROLEID, API) SELECT ROLEID, 'viewApprovedMedicalReport' FROM ROLE WHERE NAME='PATIENT';
INSERT INTO ROLE_ACCESS (ROLEID, API) SELECT  ROLEID, 'approveMedicalReport' FROM ROLE WHERE NAME='ADMIN';
INSERT INTO ROLE_ACCESS (ROLEID, API) SELECT  ROLEID,'approveMedicalReport' FROM ROLE WHERE NAME='DOCTOR';

INSERT INTO ROLE_ACCESS (ROLEID, API) SELECT ROLEID, 'addNotes' FROM ROLE WHERE NAME='PATIENT';
INSERT INTO ROLE_ACCESS (ROLEID, API) SELECT  ROLEID, 'addNotes' FROM ROLE WHERE NAME='ADMIN';
INSERT INTO ROLE_ACCESS (ROLEID, API) SELECT  ROLEID,'addNotes' FROM ROLE WHERE NAME='DOCTOR';







INSERT INTO ADDRESS_TYPE(NAME, DESCRIPTION) VALUES('HOME','Home');
INSERT INTO ADDRESS_TYPE(NAME, DESCRIPTION) VALUES('WORK','Home');
INSERT INTO ADDRESS_TYPE(NAME, DESCRIPTION) VALUES('VACATION HOME','Vacation Home');



INSERT INTO REPORT_TYPE(CODE,NAME, DESCRIPTION) VALUES('URS','Urinalysis','Urinal Analysis');
INSERT INTO REPORT_TYPE(CODE,NAME, DESCRIPTION) VALUES('BT','Blood Test','Blood Test');
INSERT INTO REPORT_TYPE(CODE,NAME, DESCRIPTION) VALUES('DT','Drugs Test','Drugs of Abuse, Urine');
INSERT INTO REPORT_TYPE(CODE,NAME, DESCRIPTION) VALUES('HT','Hepatitis','Hepatitis Panel');


INSERT INTO MEDICAL_REPORT_STATE(STATEID,NAME, DESCRIPTION) VALUES(10, 'Received', 'Medical report received from the labs');
INSERT INTO MEDICAL_REPORT_STATE(STATEID,NAME, DESCRIPTION) VALUES(20, 'Waiting for approval','Waiting for approval ');
INSERT INTO MEDICAL_REPORT_STATE(STATEID,NAME, DESCRIPTION) VALUES(30, 'Approved','Medical report approved');
INSERT INTO MEDICAL_REPORT_STATE(STATEID,NAME, DESCRIPTION) VALUES(40,'Rejected','Medical report rejected');



INSERT INTO CONTACT_TYPE(NAME, DESCRIPTION) VALUES('WORK EMAIL','Work Email');
INSERT INTO CONTACT_TYPE(NAME, DESCRIPTION) VALUES('WORK PHONE','Work PhoneNumber');
INSERT INTO CONTACT_TYPE(NAME, DESCRIPTION) VALUES('HOME PHONE','Home Phone Number');
INSERT INTO CONTACT_TYPE(NAME, DESCRIPTION) VALUES('MOBILE PHONE','Mobile Number');


INSERT INTO ORGANIZATION_TYPE(NAME, DESCRIPTION) VALUES('LAB','lab');
INSERT INTO ORGANIZATION_TYPE(NAME, DESCRIPTION) VALUES('Elderly Health Care','Elderly Health Care');
INSERT INTO ORGANIZATION_TYPE(NAME, DESCRIPTION) VALUES('Chiropractor','Chiropractor');


INSERT INTO PROVIDER_IDENTIFIER_TYPE(CODE, DESCRIPTION) VALUES('NPI','National Provider Identifier');




  