101=INSERT INTO PERSON_CONTACT(PERSONID,CONTACTTYPEID,VALUE,STATE,CREATED,UPDATED) VALUES(?,?,?,?,NOW(),NOW())
102=UPDATE PERSON_CONTACT SET CONTACTYPEID=?,VALUE=?, STATE=?, UPDATED=NOW() WHERE PCID=?
103=SELECT PCID,CONTACTTYPEID,VALUE,STATE,CREATED,UPDATED FROM PERSON_CONTACT WHERE PERSONID=? AND STATE=0
104=UPDATE PERSON_CONTACT SET STATE =1 WHERE PCID=?
