101=INSERT INTO ADDRESS(ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,COUNTRY,ZIPCODE,CREATED,UPDATED) VALUES(?,?,?,?,?,?,NOW(),NOW())
102=UPDATE ADDRESS SET ADDRESSLINE1=?,ADDRESSLINE2=?,CITY=?,STATE=?,COUNTRY=?,ZIPCODE=?,UPDATED=NOW() WHERE ADDRESSID=?
103=SELECT ADDRESSID,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,COUNTRY,ZIPCODE,CREATED,UPDATED FROM ADDRESS WHERE ADDRESSID IN (%s)
104=SELECT ADDRESSID,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,COUNTRY,ZIPCODE,CREATED,UPDATED FROM ADDRESS WHERE ADDRESSID=?