101=SELECT R.ROLEID, R.NAME, R.DESCRIPTION FROM ROLE R
102=SELECT A.ROLEID,A.API FROM ROLE_ACCESS A



201=SELECT ADDRESSTYPEID,NAME,DESCRIPTION FROM ADDRESS_TYPE


301=SELECT CONTACTTYPEID, NAME, DESCRIPTION FROM CONTACT_TYPE

401=SELECT RELATIONID, NAME, DESCRIPTION FROM RELATION_TYPE

501=SELECT STATEID, NAME, DESCRIPTION FROM MEDICAL_REPORT_STATE

601=SELECT ORGTYPEID, NAME, DESCRIPTION FROM ORGANIZATION_TYPE

701=SELECT IDENTIFIEDTYPEID, CODE, DESCRIPTION FROM PROVIDER_IDENTIFIER_TYPE